
DROP SEQUENCE ATTACH_SEQ;
DROP SEQUENCE UPLOAD_SEQ;
CREATE SEQUENCE UPLOAD_SEQ NOCACHE;
CREATE SEQUENCE ATTACH_SEQ NOCACHE;


-- 업로드 테이블
DROP TABLE UPLOAD CASCADE CONSTRAINTS;
CREATE TABLE UPLOAD (
	UPLOAD_NO	            NUMBER	            NOT NULL,
	ID	                    VARCHAR2(30 BYTE)	NOT NULL,
	UPLOAD_TITLE	            VARCHAR2(100 BYTE)	NOT NULL,
	UPLOAD_CONTENT	        VARCHAR2(100 BYTE)	NULL,
	UPLOAD_CREATE_DATE	    DATE	            NULL,
	UPLOAD_LAST_MODIFY_DATE	DATE	            NULL,
	UPLOAD_HIT	            NUMBER	            NULL,
	IP	                    VARCHAR2(30 BYTE)	NULL
);

-- 첨부파일 테이블
DROP TABLE ATTACH CASCADE CONSTRAINTS;
CREATE TABLE ATTACH (
	ATTACH_NO	            NUMBER	            NOT NULL,
	UPLOAD_NO	            NUMBER	            NOT NULL,
	ORIGIN	                VARCHAR2(300 BYTE)	NULL,
	FILESYSTEM	            VARCHAR2(40 BYTE)	NULL,
	DOWNLOAD_CNT	            NUMBER	            NULL,
	PATH	                VARCHAR2(300 BYTE)	NULL
);

-- 기본키
-- * PK 이름 : PK_자기테이블 PRIMARY KEY(PK칼럼명);
-- 1. 업로드 pk
ALTER TABLE UPLOAD ADD CONSTRAINT PK_UPLOAD PRIMARY KEY(UPLOAD_NO);

-- 2. 첨부파일 pk
ALTER TABLE ATTACH ADD CONSTRAINT PK_ATTACH PRIMARY KEY(ATTACH_NO);

-- 외래키
-- * FK 이름 : FK_자기테이블_PK가 있는테이블 FOREIGH KEY(FK칼럼명) REFERENCES PK테이블(PK칼럼명);

-- 1. 업로드 fk 
ALTER TABLE UPLOAD ADD CONSTRAINT FK_UPLOAD_USERS FOREIGN KEY(ID)
    REFERENCES USERS(ID) ON DELETE CASCADE;
-- 2. 첨부파일 fk 
ALTER TABLE ATTACH ADD CONSTRAINT FK_ATTACH_USERS FOREIGN KEY(UPLOAD_NO)
    REFERENCES UPLOAD(UPLOAD_NO) ON DELETE CASCADE;
    
    
-- 데이터 삽입
-- * FK오류 : ID칼럼을 참조하는 USERS테이블에 데이터가 있어야한다
--            이 때 USER테이블의 ID값과 INSERT문의 ID값은 동일해야한다
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디1', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디2', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디3', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디4', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디5', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디6', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디7', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디8', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디9', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디10', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디11', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디12', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디13', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디14', '제목', '내용', SYSDATE, SYSDATE, 0, NULL);
INSERT INTO UPLOAD VALUES (UPLOAD_SEQ.NEXTVAL, '아이디15', '제목', '내용', SYSDATE, SYSDATE, 0, 'ip확인');

COMMIT;
