-- [1] 회원게시판
DROP TABLE USERS;
CREATE TABLE USERS (
	USER_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	PW	VARCHAR2(64 BYTE)	NOT NULL,
	NAME	VARCHAR2(50 BYTE)	NOT NULL,
	GENDER	VARCHAR2(2 BYTE)	NOT NULL,
	EMAIL	VARCHAR2(50 BYTE)	NOT NULL,
	MOBILE	VARCHAR2(11 BYTE)	NOT NULL,
	BIRTHYEAR	VARCHAR2(4 BYTE)	NOT NULL,
	BIRTHDAY	VARCHAR2(4 BYTE)	NOT NULL,
	POSTCODE	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	EXTRA_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	AGREE_CODE	NUMBER	NOT NULL,
	SNS_TYPE	VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	DATE	NOT NULL,
	PW_MODIFY_DATE	DATE	NULL,
	INFO_MODIFY_DATE	DATE	NULL,
	SESSION_ID	VARCHAR2(32 BYTE)	NULL,
	SESSION_LIMIT_DATE	DATE	NULL,
	POINT	NUMBER	NULL
);

DROP TABLE SLEEP_USERS;

CREATE TABLE SLEEP_USERS (
	SLEEP_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NULL,
	PW	VARCHAR2(64 BYTE)	NULL,
	NAME	VARCHAR2(50 BYTE)	NULL,
	GENDER	VARCHAR2(2 BYTE)	NULL,
	EMAIL	VARCHAR2(45 BYTE)	NULL,
	MOBILE	VARCHAR2(11 BYTE)	NULL,
	BIRTHYEAR	VARCHAR2(4 BYTE)	NULL,
	BIRTHDAY	VARCHAR2(4 BYTE)	NULL,
	POSTCODE	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	AGREE_CODE	NUMBER	NULL,
	SNS_TYPE	VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	DATE	NULL,
	PW_MODIFY_DATE	DATE	NULL,
	MODIFY_DATE	DATE	NULL,
	POINT	NUMBER	NULL
);

DROP TABLE RETIRE_USERS;

CREATE TABLE RETIRE_USERS (
	RETIRE_NO	NUMBER	NOT NULL,
	JOIN_DATE	DATE	NULL,
	RETIRE_DATE	DATE	NULL,
	ID	VARCHAR2(30 BYTE)	NULL
);

DROP TABLE ACCESS_LOG;

CREATE TABLE ACCESS_LOG (
	ACCESS_LOG_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	LAST_LOGIN_DATE	DATE	NULL
);



-- [2] 자유게시판
DROP TABLE BBS;

CREATE TABLE BBS (
	BBS_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	BBS_TITLE	VARCHAR2(1000 BYTE)	NULL,
	BBS_CREATE_DATE	DATE	NULL,
	STATE	NUMBER(1)	NULL,
	DEPTH	NUMBER(2)	NULL,
	GROUP_NO	NUMBER	NULL,
	GROUP_ORDER	NUMBER	NULL,
	BSS_LAST_MODIFY_DATE	DATE	NULL,
	IP	VARCHAR2(30 BYTE)	NULL
);



-- [3] 갤러리 게시판
DROP TABLE GALLERY;
CREATE TABLE GALLERY (
	GAL_NO	NUMBER	NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	GAL_TITLE	VARCHAR2(100 BYTE)	NULL,
	GAL_CONTENT	VARCHAR2(1000 BYTE)	NULL,
	GAL_CREATE_DATE	DATE	NULL,
	GAL_LAST_MODIFY_DATE	DATE	NULL,
	GAL_HIT	NUMBER	NULL,
	LIKE_COUNT	NUMBER	NULL,
	IP	VARCHAR2(30 BYTE)	NULL
);

---------------------------------------------------------------------------------------------

-- [4] 업로드, 첨부 게시판
-- 업로드 테이블
DROP TABLE UPLOAD CASCADE CONSTRAINTS;
CREATE TABLE UPLOAD (
	UPLOAD_NO	            NUMBER	            NOT NULL,
	ID	                    VARCHAR2(30 BYTE)	NOT NULL,
	UPLOAD_TITLE	            VARCHAR2(100 BYTE)	NULL,
	UPLOAD_CONTENT	        VARCHAR2(100 BYTE)	NULL,
	UPLOAD_CREATE_DATE	    DATE	            NULL,
	UPLOAD_LAST_MODIFY_DATE	DATE	            NULL,
	UPLOAD_HIT	            NUMBER	            NULL,
	IP	                    VARCHAR2(30 BYTE)	NULL
);

-- 첨부파일 테이블
DROP TABLE ATTACH CASCADE CONSTRAINTS;
CREATE TABLE ATTACH (
	ATTACH_NO	            NUMBER	            NOT NULL,
	UPLOAD_NO	            NUMBER	            NOT NULL,
	ORIGIN	                VARCHAR2(300 BYTE)	NULL,
	FILESYSTEM	            VARCHAR2(40 BYTE)	NULL,
	DOWNLOAD_CNT	            NUMBER	            NULL,
	PATH	                VARCHAR2(300 BYTE)	NULL
);

-- 기본키
-- * PK 이름 : PK_자기테이블 PRIMARY KEY(PK칼럼명);
-- 1. 업로드 pk
ALTER TABLE UPLOAD ADD CONSTRAINT PK_UPLOAD PRIMARY KEY(UPLOAD_NO);

-- 2. 첨부파일 pk
ALTER TABLE ATTACH ADD CONSTRAINT PK_ATTACH PRIMARY KEY(ATTACH_NO);

-- 외래키
-- * FK 이름 : FK_자기테이블_PK가 있는테이블 FOREIGH KEY(FK칼럼명) REFERENCES PK테이블(PK칼럼명);

-- 1. 업로드 fk 
ALTER TABLE UPLOAD ADD CONSTRAINT FK_UPLOAD_USERS FOREIGN KEY(ID)
    REFERENCES USERS(ID);
-- 2. 첨부파일 fk 
ALTER TABLE ATTACH ADD CONSTRAINT FK_ATTACH_USERS FOREIGN KEY(UPLOAD_NO)
    REFERENCES UPLOAD(UPLOAD_NO);



---------------------------------------------------------------------------------------------


DROP TABLE USERS;

CREATE TABLE USERS (
	USER_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	PW	VARCHAR2(64 BYTE)	NOT NULL,
	NAME	VARCHAR2(50 BYTE)	NOT NULL,
	GENDER	VARCHAR2(2 BYTE)	NOT NULL,
	EMAIL	VARCHAR2(50 BYTE)	NOT NULL,
	MOBILE	VARCHAR2(11 BYTE)	NOT NULL,
	BIRTHYEAR	VARCHAR2(4 BYTE)	NOT NULL,
	BIRTHDAY	VARCHAR2(4 BYTE)	NOT NULL,
	POSTCODE	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	EXTRA_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	AGREE_CODE	NUMBER	NOT NULL,
	SNS_TYPE	VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	DATE	NOT NULL,
	PW_MODIFY_DATE	DATE	NULL,
	INFO_MODIFY_DATE	DATE	NULL,
	SESSION_ID	VARCHAR2(32 BYTE)	NULL,
	SESSION_LIMIT_DATE	DATE	NULL,
	POINT	NUMBER	NULL
);

DROP TABLE SLEEP_USERS;

CREATE TABLE SLEEP_USERS (
	SLEEP_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NULL,
	PW	VARCHAR2(64 BYTE)	NULL,
	NAME	VARCHAR2(50 BYTE)	NULL,
	GENDER	VARCHAR2(2 BYTE)	NULL,
	EMAIL	VARCHAR2(45 BYTE)	NULL,
	MOBILE	VARCHAR2(11 BYTE)	NULL,
	BIRTHYEAR	VARCHAR2(4 BYTE)	NULL,
	BIRTHDAY	VARCHAR2(4 BYTE)	NULL,
	POSTCODE	VARCHAR2(5 BYTE)	NULL,
	ROAD_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	JIBUN_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	DETAIL_ADDRESS	VARCHAR2(100 BYTE)	NULL,
	AGREE_CODE	NUMBER	NULL,
	SNS_TYPE	VARCHAR2(10 BYTE)	NULL,
	JOIN_DATE	DATE	NULL,
	PW_MODIFY_DATE	DATE	NULL,
	MODIFY_DATE	DATE	NULL,
	POINT	NUMBER	NULL
);

DROP TABLE RETIRE_USERS;

CREATE TABLE RETIRE_USERS (
	RETIRE_NO	NUMBER	NOT NULL,
	JOIN_DATE	DATE	NULL,
	RETIRE_DATE	DATE	NULL,
	ID	VARCHAR2(30 BYTE)	NULL
);

DROP TABLE ACCESS_LOG;

CREATE TABLE ACCESS_LOG (
	ACCESS_LOG_NO	NUMBER	NOT NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	LAST_LOGIN_DATE	DATE	NULL
);

DROP TABLE LIKE;

CREATE TABLE LIKE (
	LIKE_NO	NUMBER	NOT NULL,
	GAL_NO	NUMBER	NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	LIKE_DATE	DATE	NULL
);

DROP TABLE COMMENT;

CREATE TABLE COMMENT (
	COMMENT_NO	NUMBER	NULL,
	GAL_NO	NUMBER	NULL,
	ID	VARCHAR2(30 BYTE)	NOT NULL,
	COMMENT_TITLE	VARCHAR2(100 BYTE)	NULL,
	COMMENT_CREATE_DATE	DATE	NULL,
	COMMNET_LAST_MODIFY_DATE	DATE	NULL,
	IP	VARCHAR2(30 BYTE)	NULL
);

ALTER TABLE BBS ADD CONSTRAINT PK_BBS PRIMARY KEY (
	BBS_NO,
	ID
);

ALTER TABLE GALLERY ADD CONSTRAINT PK_GALLERY PRIMARY KEY (
	GAL_NO,
	ID
);

ALTER TABLE UPLOAD ADD CONSTRAINT PK_UPLOAD PRIMARY KEY (
	UPLOAD_NO,
	ID
);

ALTER TABLE ATTACH ADD CONSTRAINT PK_ATTACH PRIMARY KEY (
	ATTACH_NO,
	UPLOAD_NO
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (
	USER_NO,
	ID
);

ALTER TABLE SLEEP_USERS ADD CONSTRAINT PK_SLEEP_USERS PRIMARY KEY (
	SLEEP_NO
);

ALTER TABLE RETIRE_USERS ADD CONSTRAINT PK_RETIRE_USERS PRIMARY KEY (
	RETIRE_NO
);

ALTER TABLE ACCESS_LOG ADD CONSTRAINT PK_ACCESS_LOG PRIMARY KEY (
	ACCESS_LOG_NO,
	ID
);

ALTER TABLE LIKE ADD CONSTRAINT PK_LIKE PRIMARY KEY (
	LIKE_NO,
	GAL_NO,
	ID
);

ALTER TABLE COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY (
	COMMENT_NO,
	GAL_NO,
	ID
);

ALTER TABLE BBS ADD CONSTRAINT FK_USERS_TO_BBS_1 FOREIGN KEY (
	ID
)
REFERENCES USERS (
	ID
);

ALTER TABLE GALLERY ADD CONSTRAINT FK_USERS_TO_GALLERY_1 FOREIGN KEY (
	ID
)
REFERENCES USERS (
	ID
);

ALTER TABLE UPLOAD ADD CONSTRAINT FK_USERS_TO_UPLOAD_1 FOREIGN KEY (
	ID
)
REFERENCES USERS (
	ID
);

ALTER TABLE ATTACH ADD CONSTRAINT FK_UPLOAD_TO_ATTACH_1 FOREIGN KEY (
	UPLOAD_NO
)
REFERENCES UPLOAD (
	UPLOAD_NO
);

ALTER TABLE ACCESS_LOG ADD CONSTRAINT FK_USERS_TO_ACCESS_LOG_1 FOREIGN KEY (
	ID
)
REFERENCES USERS (
	ID
);

ALTER TABLE LIKE ADD CONSTRAINT FK_GALLERY_TO_LIKE_1 FOREIGN KEY (
	GAL_NO
)
REFERENCES GALLERY (
	GAL_NO
);

ALTER TABLE LIKE ADD CONSTRAINT FK_USERS_TO_LIKE_1 FOREIGN KEY (
	ID
)
REFERENCES USERS (
	ID
);

ALTER TABLE COMMENT ADD CONSTRAINT FK_GALLERY_TO_COMMENT_1 FOREIGN KEY (
	GAL_NO
)
REFERENCES GALLERY (
	GAL_NO
);

ALTER TABLE COMMENT ADD CONSTRAINT FK_USERS_TO_COMMENT_1 FOREIGN KEY (
	ID
)
REFERENCES USERS (
	ID
);
