-- 시퀸스
DROP SEQUENCE MOVIE_SEQ;
CREATE SEQUENCE MOVIE_SEQ NOCACHE;

-- 테이블
DROP TABLE MOVIE;
CREATE TABLE MOVIE(
    NO NUMBER                       NOT NULL,
    TITLE VARCHAR2(100 BYTE)        NULL,
    GENRE VARCHAR2(100 BYTE)        NULL,
    DESCRIPTION VARCHAR2(500 BYTE)  NULL,
    STAR NUMBER                     NULL
);

-- 기본키
ALTER TABLE MOVIE
    ADD CONSTRAINT PK_MOVIE PRIMARY KEY(NO);