DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_LOG CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
    MEMBER_NO NUMBER             NOT NULL,
    ID VARCHAR2(30 BYTE) UNIQUE  NOT NULL,
    PW VARCHAR2(30 BYTE)        NOT NULL,
    NAME VARCHAR2(30 BYTE),
    PHONE VARCHAR2(15 BYTE)
);

CREATE TABLE MEMBER_LOG(
    LOG_NO NUMBER  NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    LOGIN DATE
);


ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NO);
ALTER TABLE MEMBER_LOG ADD CONSTRAINT PK_MEMBER_LOG PRIMARY KEY(LOG_NO);
ALTER TABLE MEMBER_LOG 
    ADD CONSTRAINT FK_MEMBER_LOG_MEMBER FOREIGN KEY(MEMBER_NO)
        REFERENCES MEMBER(MEMBER_NO);
        
        -- UNIQUE
        -- NOT NULL
        -- FK(생략)

