
-- 1. DDL 테이블 삭제, 생성, 추가

-- 테이블 삭제

DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE PROFESSOR CASCADE CONSTRAINTS;
DROP TABLE LECTURE CASCADE CONSTRAINTS;
DROP TABLE ENROLL CASCADE CONSTRAINTS;
DROP TABLE COURSE CASCADE CONSTRAINTS;

/*
교수 - 강의
학생 - 수강신청
수강신청 - 강의
*/

-- 테이블 생성

CREATE TABLE STUDENT(
    STU_STUNUM VARCHAR2(20 BYTE) NOT NULL,             --PK
    STU_NAME VARCHAR2(20 BYTE),
    STU_AD VARCHAR2(30 BYTE),
    STU_NUM NUMBER(1),           
    STU_TENUM NUMBER 
);

CREATE TABLE PROFESSOR(
    PRO_NUM VARCHAR2(20 BYTE) NOT NULL,     --PK
    PRO_NAME VARCHAR2(15 BYTE),
    PRO_STU VARCHAR2(15 BYTE)
);

CREATE TABLE COURSE(
    COUR_NUM VARCHAR2(15 BYTE) NOT NULL,
    COUR_NAME VARCHAR2(20 BYTE),
    SCORE CHAR(1)
);

CREATE TABLE ENROLL(
    APLI_NUM VARCHAR2(15 BYTE) NOT NULL,    --PK
    STU_STUNUM VARCHAR2(20 BYTE),           --FK
    COUR_NUM VARCHAR2(15 BYTE),
    APLIDAY VARCHAR2(15 BYTE)
);
CREATE TABLE LECTURE(
    LEC_NUM VARCHAR2(15 BYTE) NOT NULL,    -- PK
    PRO_NUM VARCHAR2(20 BYTE) NOT NULL,  --FK
    APLI_NUM VARCHAR2(15 BYTE),             --FK
    LEC_NAME VARCHAR2(20 BYTE),
    LEC_CLAS VARCHAR2(20 BYTE)
);

-- 기본키, 외래키 추가
ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_STUNUM); 
ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NUM);
ALTER TABLE COURSE ADD CONSTRAINT PK_COURSE PRIMARY KEY(COUR_NUM);
ALTER TABLE ENROLL ADD CONSTRAINT PK_ENROLL PRIMARY KEY(APLI_NUM);
ALTER TABLE LECTURE ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NUM);

ALTER TABLE ENROLL ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_STUNUM) 
    REFERENCES STUDENT(STU_STUNUM) ON DELETE SET NULL;
ALTER TABLE ENROLL ADD CONSTRAINT FK_ENROLL_COURSE 
    FOREIGN KEY(COUR_NUM) REFERENCES COURSE(COUR_NUM);
ALTER TABLE LECTURE ADD CONSTRAINT FK_LECTURE_PROFESSOR 
    FOREIGN KEY(PRO_NUM) REFERENCES PROFESSOR(PRO_NUM) ON DELETE CASCADE;
ALTER TABLE LECTURE ADD CONSTRAINT FK_LECTURE_ENROLL 
    FOREIGN KEY(APLI_NUM) REFERENCES ENROLL(APLI_NUM);
    
-- 2. DML 객체값 추가, 수정, 삭제

-- 1) 학생 추가
INSERT INTO STUDENT(STU_STUNUM, STU_NAME) VALUES(1001, '김김김');
INSERT INTO STUDENT(STU_STUNUM, STU_NAME) VALUES(1002, '이이이');
INSERT INTO STUDENT(STU_STUNUM, STU_NAME) VALUES(1003, '박박박');

-- 2) 교수 추가
INSERT INTO PROFESSOR(PRO_NAME) VALUES('해해해');
INSERT INTO PROFESSOR(PRO_NUM, PRO_NAME) VALUES(102, '신신신');
INSERT INTO PROFESSOR(PRO_NUM, PRO_NAME) VALUES(103, '고고고');

-- 3) 과목 추가
INSERT INTO COURSE(APLI_NUM, COUR_NAME) VALUES(1, '수학');
INSERT INTO COURSE(APLI_NUM, COUR_NAME) VALUES(2, '영어');
INSERT INTO COURSE(APLI_NUM, COUR_NAME) VALUES(3, '국어');

-- 4) 수강신청 추가
INSERT INTO ENROLL(COUR_NUM, STU_STUNUM) VALUES(3, '3');
INSERT INTO ENROLL(COUR_NUM, STU_STUNUM) VALUES(3, '2');
INSERT INTO ENROLL(COUR_NUM, STU_STUNUM) VALUES(3, '1');

-- 5) 강의 추가















